version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build:
    steps:
      - checkout
      - npm install
      - npm run test
  # test:
  #   steps:
  #     - checkout
  #     - run: <command>
workflows:
  build_and_test:
    jobs: 
      - build
      # - test
