version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:14.13.0
    steps:
      - checkout
      - node --version
      - npm install
      - npm run test

workflows:
  build_and_test:
    jobs: 
      - build
      # - test
