version: 2.1
jobs:
  build:
    docker:
      - image: cypress/browsers:node12.14.1-chrome85-ff81
    steps:
      - checkout
      - run: node --version
      - run: npm install
      - run: npm run test -- --record --key 52cc57a1-e3a8-4c60-b1f5-c12d300e5398

workflows:
  build_and_test:
    jobs: 
      - build
      # - test
